### ISSUE TITLE
yarn not found

### ISSUE THREAD

**Issue by markfirmware** [jonalvarezz/snowpack-template-tailwind#1]
npm i -g yarn
    npx create-snowpack-app --template snowpack-template-tailwind --use-yarn tailwind
    npx: installed 29 in 10.787s
    [ERROR] Yarn doesn't seem to be installed.

**Comment by jonalvarezz** [comment]
Thank you! 

In fact `yarn` has to be installed before using the `--use-yarn` param. 

I removed the optional yarn parameter from the README to avoid confusion

**Comment by jonalvarezz** [comment]
https://github.com/jonalvarezz/snowpack-template-tailwind/releases/tag/0.3.1
